Source    = \
	JsonConverter.java \
	JsonWriter.java \
	Quantity.java \
	Unit.java \
	UnitManager.java \
        XmlUtil.java \
	display_symbols.txt \
	unit_aliases.txt \
	witsmlUnitDict-2.2.xml \
	Energistics_Unit_of_Measure_Dictionary.json \
	uom.json \

Main = UnitManager

include $(DEV_HOME)/osdu-uom/Makefile