ProjectDisplayName = UoM

# This makefile is only used to inject Google Analytics code into
# the documentation html:
#
#  $ doxygen
#  $ make analytics
#
# Or count LOC:
#
#  $ make loc

include $(DEV_HOME)/tools/Make/Makefile
