ProjectDisplayName = OSDU - UoM

JavaPackages = \
        no/geosoft/uom \

JavadocPackages = -subpackages no

JavaLibraries = \
	javax.json-1.1.3.jar \
	javax.json-api-1.1.3.jar \

include $(DEV_HOME)/tools/Make/Makefile
