ProjectDisplayName = UoM

JavaPackages = \
        no/geosoft/uom \

JavadocPackages = -subpackages no

JavaLibraries = \
	javax.json-1.1.3.jar \
	javax.json-api-1.1.3.jar \
	justify-0.15.0.jar \

JavaMainClass = no.geosoft.uom.UnitManager

include $(DEV_HOME)/tools/Make/Makefile
